file,time,cmd_output,err_output,Uniform,Timeout
/home/gilles/GillesTestModels/toybox2.cnf,60.055,,,N/A,TRUE
/home/gilles/GillesTestModels/s38417_3_2.cnf,60.047,,,N/A,TRUE
/home/gilles/GillesTestModels/s38584_7_4.cnf,60.058,,,N/A,TRUE
/home/gilles/GillesTestModels/coreboot.cnf,0.817,b'Input file:  /home/gilles/GillesTestModels/coreboot.cnf\nNumber of samples:  1\nOutput directory: /home/gilles/GillesTestModels\nCounting - Experiment: 0     of     1\nconstantFactor:39   boundFactor: 14.541336623567457   logBoundFactor: 3.8620879811712894  \ntj: 1789   totalLoops: 2     beta: 0.8181818181818182 epsilon: 0.3       \nnumSolutions: 568   loThresh:82     hiThresh: 485   \n*** Progress *** i: 0 j: 2 ---- 0 / 3578\nUsing sampler: SMARCH\ncmd:  python3 ./samplers/smarch_mp.py -p 4 -o /home/gilles/GillesTestModels /home/gilles/GillesTestModels/coreboot.cnf 1\n/home/gilles/GillesTestModels/coreboot_1.samples\n',"b'Traceback (most recent call last):\n  File ""./samplers/smarch_mp.py"", line 493, in <module>\n    samples = master(vcount, clauses, n, wdir, const, threads, quiet)\n  File ""./samplers/smarch_mp.py"", line 249, in master\n    freevar = partition([], vcount_, clauses_, wdir_)\n  File ""./samplers/smarch_mp.py"", line 198, in partition\n    if out[7].startswith(\'c all\'):\nIndexError: list index out of range\nTraceback (most recent call last):\n  File ""barbarik.py"", line 1089, in <module>\n    ok, breakExperiment = exp.one_experiment(experiment, j, i, numExperiments, tj)\n  File ""barbarik.py"", line 962, in one_experiment\n    self.inputFile, 1, self.samplerType, self.indVarList, newSeed)\n  File ""barbarik.py"", line 190, in getSolutionFromSampler\n    sols = SolutionRetriver.getSolutionFromSMARCH(*topass_withseed)\n  File ""barbarik.py"", line 604, in getSolutionFromSMARCH\n    df= pd.read_csv(tempFile,header=None)\n  File ""/home/gilles/.local/lib/python3.6/site-packages/pandas/io/parsers.py"", line 676, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File ""/home/gilles/.local/lib/python3.6/site-packages/pandas/io/parsers.py"", line 448, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File ""/home/gilles/.local/lib/python3.6/site-packages/pandas/io/parsers.py"", line 880, in __init__\n    self._make_engine(self.engine)\n  File ""/home/gilles/.local/lib/python3.6/site-packages/pandas/io/parsers.py"", line 1114, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File ""/home/gilles/.local/lib/python3.6/site-packages/pandas/io/parsers.py"", line 1891, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File ""pandas/_libs/parsers.pyx"", line 374, in pandas._libs.parsers.TextReader.__cinit__\n  File ""pandas/_libs/parsers.pyx"", line 674, in pandas._libs.parsers.TextReader._setup_parser_source\nFileNotFoundError: [Errno 2] File /home/gilles/GillesTestModels/coreboot_1.samples does not exist: \'/home/gilles/GillesTestModels/coreboot_1.samples\'\n'",N/A,FALSE
/home/gilles/GillesTestModels/s27_7_4.cnf,60.059,,,N/A,TRUE
/home/gilles/GillesTestModels/busybox-1.18.0.cnf,60.059,,,N/A,TRUE
/home/gilles/GillesTestModels/FM-3.6.1-refined.cnf,60.060,,,N/A,TRUE
/home/gilles/GillesTestModels/blasted_TR_ptb_2_linear.cnf,60.004,,,N/A,TRUE
/home/gilles/GillesTestModels/toybox.cnf,60.057,,,N/A,TRUE
/home/gilles/GillesTestModels/blasted_case110.cnf,60.064,,,N/A,TRUE
/home/gilles/GillesTestModels/s27_3_2.cnf,60.058,,,N/A,TRUE
/home/gilles/GillesTestModels/s713_15_7.cnf,17.398,b'Input file:  /home/gilles/GillesTestModels/s713_15_7.cnf\nNumber of samples:  1\nOutput directory: /home/gilles/GillesTestModels\nCounting - Total configurations: 10099441247715328\n1124: Sampling 0 with 5685126032795290 - sampling time: 4.970142364501953\n--- total time: 5.7611634731292725 seconds ---\nOutput samples created on:  /home/gilles/GillesTestModels/s713_15_7_1.samples\nInput file:  /tmp/s713_15_7_t.cnf\nNumber of samples:  568\nOutput directory: /tmp\nCounting - Total configurations: 7157287750\n1926: Sampling 0 with 4252399044 - 1927: Sampling 0 with 5918747686 - 1925: Sampling 0 with 90976260 - 1924: Sampling 0 with 2523994360 - --- total time: 0.5622758865356445 seconds ---\nOutput samples created on:  /tmp/s713_15_7_t_568.samples\nExperiment: 0     of     1\nconstantFactor:39   boundFactor: 14.541336623567457   logBoundFactor: 3.8620879811712894  \ntj: 1789   totalLoops: 2     beta: 0.8181818181818182 epsilon: 0.3       \nnumSolutions: 568   loThresh:82     hiThresh: 485   \n*** Progress *** i: 0 j: 2 ---- 0 / 3578\nUsing sampler: SMARCH\ncmd:  python3 ./samplers/smarch_mp.py -p 4 -o /home/gilles/GillesTestModels /home/gilles/GillesTestModels/s713_15_7.cnf 1\n/home/gilles/GillesTestModels/s713_15_7_1.samples\nNumber of solutions returned by sampler: 1\nUsing sampler: KUS\ncmd:  python3  KUS.py --samples=1 --outputfile /tmp/s713_15_7.txt /home/gilles/GillesTestModels/s713_15_7.cnf > /dev/null 2>&1\nNumber of solutions returned by sampler: 1\nUsing sampler: SMARCH\ncmd:  python3 ./samplers/smarch_mp.py -p 4 -o /tmp /tmp/s713_15_7_t.cnf 568\n/tmp/s713_15_7_t_568.samples\n',"b'Process Process-4:\nTraceback (most recent call last):\n  File ""/usr/lib/python3.6/multiprocessing/process.py"", line 258, in _bootstrap\n    self.run()\n  File ""/usr/lib/python3.6/multiprocessing/process.py"", line 93, in run\n    self._target(*self._args, **self._kwargs)\n  File ""./samplers/smarch_mp.py"", line 367, in sample\n    r_freevar = partition(assigned, vcount_, clauses_, _wdir)\n  File ""./samplers/smarch_mp.py"", line 214, in partition\n    res = int(getoutput(SHARPSAT + \' -q \' + _dimacsfile))\nValueError: invalid literal for int() with base 10: \'\\n FOUND UNSAT DURING PREPROCESSING \\n0\'\nProcess Process-5:\nTraceback (most recent call last):\n  File ""/usr/lib/python3.6/multiprocessing/process.py"", line 258, in _bootstrap\n    self.run()\n  File ""/usr/lib/python3.6/multiprocessing/process.py"", line 93, in run\n    self._target(*self._args, **self._kwargs)\n  File ""./samplers/smarch_mp.py"", line 367, in sample\n    r_freevar = partition(assigned, vcount_, clauses_, _wdir)\n  File ""./samplers/smarch_mp.py"", line 214, in partition\n    res = int(getoutput(SHARPSAT + \' -q \' + _dimacsfile))\nValueError: invalid literal for int() with base 10: \'\\n FOUND UNSAT DURING PREPROCESSING \\n0\'\nProcess Process-3:\nTraceback (most recent call last):\n  File ""/usr/lib/python3.6/multiprocessing/process.py"", line 258, in _bootstrap\n    self.run()\n  File ""/usr/lib/python3.6/multiprocessing/process.py"", line 93, in run\n    self._target(*self._args, **self._kwargs)\n  File ""./samplers/smarch_mp.py"", line 367, in sample\n    r_freevar = partition(assigned, vcount_, clauses_, _wdir)\n  File ""./samplers/smarch_mp.py"", line 214, in partition\n    res = int(getoutput(SHARPSAT + \' -q \' + _dimacsfile))\nValueError: invalid literal for int() with base 10: \'\\n FOUND UNSAT DURING PREPROCESSING \\n0\'\nProcess Process-2:\nTraceback (most recent call last):\n  File ""/usr/lib/python3.6/multiprocessing/process.py"", line 258, in _bootstrap\n    self.run()\n  File ""/usr/lib/python3.6/multiprocessing/process.py"", line 93, in run\n    self._target(*self._args, **self._kwargs)\n  File ""./samplers/smarch_mp.py"", line 367, in sample\n    r_freevar = partition(assigned, vcount_, clauses_, _wdir)\n  File ""./samplers/smarch_mp.py"", line 214, in partition\n    res = int(getoutput(SHARPSAT + \' -q \' + _dimacsfile))\nValueError: invalid literal for int() with base 10: \'\\n FOUND UNSAT DURING PREPROCESSING \\n0\'\nTraceback (most recent call last):\n  File ""barbarik.py"", line 1089, in <module>\n    ok, breakExperiment = exp.one_experiment(experiment, j, i, numExperiments, tj)\n  File ""barbarik.py"", line 990, in one_experiment\n    self.tempFile, self.numSolutions, self.samplerType, tempIndVarList, newSeed)\n  File ""barbarik.py"", line 190, in getSolutionFromSampler\n    sols = SolutionRetriver.getSolutionFromSMARCH(*topass_withseed)\n  File ""barbarik.py"", line 604, in getSolutionFromSMARCH\n    df= pd.read_csv(tempFile,header=None)\n  File ""/home/gilles/.local/lib/python3.6/site-packages/pandas/io/parsers.py"", line 676, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File ""/home/gilles/.local/lib/python3.6/site-packages/pandas/io/parsers.py"", line 448, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n  File ""/home/gilles/.local/lib/python3.6/site-packages/pandas/io/parsers.py"", line 880, in __init__\n    self._make_engine(self.engine)\n  File ""/home/gilles/.local/lib/python3.6/site-packages/pandas/io/parsers.py"", line 1114, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File ""/home/gilles/.local/lib/python3.6/site-packages/pandas/io/parsers.py"", line 1891, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File ""pandas/_libs/parsers.pyx"", line 532, in pandas._libs.parsers.TextReader.__cinit__\npandas.errors.EmptyDataError: No columns to parse from file\n'",N/A,FALSE
